# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # BuyerOrg
  # ---------------------------------------------------------------------------
  - Name: BuyerOrg
    Domain: buyer.freshroute.com
    EnableNodeOUs: true

    # ---------------------------------------------------------------------------
    # "CA"
    # ---------------------------------------------------------------------------
    CA:
      Hostname: ca # implicitly ca.buyer.freshroute.com
      SANS:
        - localhost

    # ---------------------------------------------------------------------------
    # "Specs"
    # ---------------------------------------------------------------------------
    Template:
      Count: 2
      SANS:
        - localhost

    # ---------------------------------------------------------------------------
    # "Users"
    # ---------------------------------------------------------------------------
    Users:
      Count: 1
